### ISSUE TITLE
Deposit QR code should be visible and usable across all responsive screen resolutions 

### ISSUE THREAD

**Issue by okjodom** [GETLN/mintgate#19]
[Screencast from 2023-01-20 12:00:11 PM.webm](https://user-images.githubusercontent.com/11217077/213796270-3518e6de-d169-46eb-8950-ed0d9d67f477.webm)

**Comment by IgboPharaoh** [comment]
Ohh, I've noticed this on my end too. The fixes I made earlier didn't cover this. 
But I'll look into fixing this

**Comment by okjodom** [comment]
closed by #26
